-- MySQL Script generated by MySQL Workbench
-- Wed Apr 27 13:43:03 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_blog_pessoal
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_blog_pessoal
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_blog_pessoal` DEFAULT CHARACTER SET utf8 ;
USE `db_blog_pessoal` ;

-- -----------------------------------------------------
-- Table `db_blog_pessoal`.`Users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_blog_pessoal`.`Users` (
  `idUsers` BIGINT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `user` VARCHAR(10) NOT NULL,
  `password` VARCHAR(15) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `phone` VARCHAR(15) NOT NULL,
  `country` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idUsers`),
  UNIQUE INDEX `user_UNIQUE` (`user` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_blog_pessoal`.`Category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_blog_pessoal`.`Category` (
  `idtable1` BIGINT GENERATED ALWAYS AS () VIRTUAL,
  `nameCateg` VARCHAR(30) NOT NULL,
  `description` TEXT NULL,
  PRIMARY KEY (`idtable1`),
  UNIQUE INDEX `nomeCateg_UNIQUE` (`nameCateg` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_blog_pessoal`.`Product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_blog_pessoal`.`Product` (
  `idProduct` BIGINT NOT NULL,
  `nameProduct` VARCHAR(30) NOT NULL,
  `price` DOUBLE NOT NULL,
  `photo` VARCHAR(45) NULL,
  `Users_idUsers` BIGINT NOT NULL,
  `Category_idtable1` BIGINT NOT NULL,
  PRIMARY KEY (`idProduct`, `Users_idUsers`, `Category_idtable1`),
  UNIQUE INDEX `nomeProduto_UNIQUE` (`nameProduct` ASC) VISIBLE,
  INDEX `fk_Product_Users_idx` (`Users_idUsers` ASC) VISIBLE,
  INDEX `fk_Product_Category1_idx` (`Category_idtable1` ASC) VISIBLE,
  CONSTRAINT `fk_Product_Users`
    FOREIGN KEY (`Users_idUsers`)
    REFERENCES `db_blog_pessoal`.`Users` (`idUsers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Product_Category1`
    FOREIGN KEY (`Category_idtable1`)
    REFERENCES `db_blog_pessoal`.`Category` (`idtable1`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_blog_pessoal`.`tb_temas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_blog_pessoal`.`tb_temas` (
  `idtb_temas` BIGINT NOT NULL,
  `descricao` TEXT NULL,
  PRIMARY KEY (`idtb_temas`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_blog_pessoal`.`tb_usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_blog_pessoal`.`tb_usuarios` (
  `idtb_usuarios` BIGINT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `usuario` VARCHAR(25) NOT NULL,
  `senha` VARCHAR(25) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `dataNascimento` DATE NOT NULL,
  `foto` VARCHAR(255) NULL,
  PRIMARY KEY (`idtb_usuarios`),
  UNIQUE INDEX `usuario_UNIQUE` (`usuario` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_blog_pessoal`.`tb_postagens`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_blog_pessoal`.`tb_postagens` (
  `idtb_postagens` BIGINT NOT NULL,
  `titulo` VARCHAR(45) NOT NULL,
  `texto` LONGTEXT NOT NULL,
  `data` DATETIME NOT NULL,
  `id_temas` BIGINT NOT NULL,
  `id_usuarios` BIGINT NOT NULL,
  PRIMARY KEY (`idtb_postagens`),
  INDEX `fk_tb_postagens_tb_temas1_idx` (`id_temas` ASC) VISIBLE,
  INDEX `fk_tb_postagens_tb_usuarios1_idx` (`id_usuarios` ASC) VISIBLE,
  CONSTRAINT `fk_tb_postagens_tb_temas1`
    FOREIGN KEY (`id_temas`)
    REFERENCES `db_blog_pessoal`.`tb_temas` (`idtb_temas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_postagens_tb_usuarios1`
    FOREIGN KEY (`id_usuarios`)
    REFERENCES `db_blog_pessoal`.`tb_usuarios` (`idtb_usuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
